[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false

[theme]
base = "dark"
primaryColor = "#9A7DFF"
backgroundColor = "#1A1A1A"
secondaryBackgroundColor = "#2D2D2D"
textColor = "#FFFFFF"
font = "sans serif"

[browser]
gatherUsageStats = false

[ui]
showSidebarNavigation = false
showFooter = false
showHeader = false
showToolbar = false
