[server]
headless = true
address = "0.0.0.0"
port = 8501

[theme]
primaryColor = "#6A39D0"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#E5E9F2"
textColor = "#333333"
font = "sans serif"

[browser]
gatherUsageStats = false

[ui]
showSidebarNavigation = false