[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false

[theme]
base = "dark"
primaryColor = "#2563EB"  # Professional blue
backgroundColor = "#0F172A"  # Deep navy
secondaryBackgroundColor = "#1E293B"  # Dark slate
textColor = "#F8FAFC"  # Bright white
font = "sans serif"

[browser]
gatherUsageStats = false

[ui]
showSidebarNavigation = false
showFooter = false
showHeader = false
showToolbar = false

